language: python

python: 3.5

env: TOXENV=py35 TRAV_DIST="sdist bdist_wheel"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - "./miniconda.sh -b"
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose
  - pip install jinja2

script:
  - "./nosetest.py"

deploy:
  - provider: releases
    api_key:
    on:
      repo: joelfrederico/SciSalt
      tags: true
  - provider: pypi
    user: JoelFrederico
    password:
    on:
      tags: true
      repo: joelfrederico/SciSalt

notifications:
  slack:
    secure: USxa0Yr5JCu2P84rIlV1LEXAQZwOnVkqQ/16aPqqpSr8QIA0kB4TmsIw+0pxrZc2/OuMpub3Yml+1ArxfEjtpyc6iJ90ED9POtqPdK364f806+fCLWeVobfSx0IQAJ6Bk9iX8IWqv8md1HBxtV4AGgeNrd6OiJYXoIHEV4yjd0kOI6v6g551E7fBTqmwYGQaPJVG7WiJLNJksZKTquW26uhQ8IISEIM91nai2KihERfmwQrVEb6ReP2WzufoJiQRjaIZVHFbtFN2nMmIiw2NbqQtlWv1/SR01uZuQzye5nh9hKi/gEbjaOGsvrTqg1lue2wY65NmLIr7lEvavro3IoCi7vqkcTq81xNc6C8KfIofTy8e5zRGp10XNMxcvnr4qdFeEh8Ze8d8CB5K0Plw7jPfh44heV413RKPmLCcjrPcwoGC5fvRU3BRGxrjems/zGqymAtMJxtJscI0j6leNoGbdp2w4tfij43zzcVDT1u3mjcm6NKWW7BNU2YG6kiSwVdModxs9/OCilEcUb+v+o8Ysc5oPgz2qgPffrRVMoF518m6IfkMszrKN4Mnn57HxqjZ9jkiWvNQx8qjCVzzD+I5KI/GHWfH15w1xxQFDInJyIDTvnjTRAVkWFs53He/YHCZ/H5VMZO1UzCFQgJRndEUfBYsuVSBshSeQZ9BvM8=
  email: false
