language: python

python: 3.5

env: TOXENV=py35 TRAV_DIST="sdist bdist_wheel"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - "./miniconda.sh -b"
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose
  - pip install jinja2 periodictable

script:
  - "./nosetest.py"

deploy:
  - provider: releases
    api_key:
      secure: ESaR/dG51htFp9VZ7h3Wj7w1rf3u524LX6i+3aeJRK/rCWLLYBOAf54S9clcPRS/EZwZNyRquBW8JqtapLYkORFth2tCxaSMKQE9eJr+1kXa76dBgzE+MSzjC8jX/h3wVpdiEutF7eKA+V4lDuwfUlx3vpCMCTd2XS8889YnU1W2LOVo5s2/VCR3wBplqQkRGKdE4RG9LSA6WG+4WaFm4CEI6PJBLvPwDlUgw4s5YQtN2fWitzwg0fzatNZuBxJPy+xXDRpC6cIKfT+AtUnXxSPLYYMuLGJOhgmFHe+7GYP5m9gkLgtZOKQJ3IHc5YTeB37uOvHe9ugOKEkgSrDykH/stpoMs3pgjDDL258Ag5JzI1gHfSoSooRkkD8yK/BdeN/d41Nww/scUH07oGdA/YqUzI+bKb2xK/tYILHNdXCxk/DwGmGF5DjHgHHL3U5uCSM3B9tmMSXCHbvHbv5ybRUPWYiU8eF52b/9xRE3wYJ2d+/G8GDe+SnVGRuYexUgOh6jsv+CpKV1OxpNuVkCFSy2EW8aEnBc1e4kciiz7V5CEcrn9WHoGtIiBzV3Vp+M/OhDUtKNMdcP9rNp8m/gl2w0Sec+xNI8xhQs4rsQZSGQbsmAGLlPbHiLWBU4wPadsRTEmV6vEWWYld1i7WcP+EiyzAGuM1XVraGvoWyIpLM=
    on:
      repo: joelfrederico/SciSalt
      tags: true
  - provider: pypi
    user: JoelFrederico
    password:
      secure: Hlt8jt0a+8JnuP2nfZnDOO5XOXZsITtg6TuEx4bC0Lz1sJjAm95DOzhUgNwf3oAPJcgF1uzJaCURmjNKDr+AH5Cki23lT0S09gdb0mxpTzN1NPvOJThIn7SWJumI3K+3C/lkqZpN8GffrsN5tU0MoT5VChsOnC2oaroxNRr6nzMgywqrBcP5kdIbU/3wlvM0kUOCH11Z7VXmVnmh/S3N7gKbqSQ3IdkMwgAcg53kARraTLwo/fgeoRDBTsVB1/lF/kF+u2EuvnFJavGhpiES9Cj/MC+0PQH72BoermNTR6lRWuMdVW3NQbV+TF4n17otehCxVpdNbMv3yyDKdweYk17u5WqPsbSlOXQZ0vXxoWcaYRpnmc1T5c39YDK3qBv0I3mr/q9OIn/3XEbN356i91LZQKUNg12CY0wLpVUAnn0sQsCfHphIieiYk3/M+GXJOqRXjHE0Fuy8ymCxnzia+ykb0HN7lO6z0uaYkPnWaAYDoBs3jEbfXTG5W7GLKmmD9zXgHFP6m62aLMLk5oIUtWbygQwey5Q1tyfSJgZP+AFeTZ1HZwEkmZFmLdesfTzIjxd5JQeB8oniKbj3FyEbMwns2ddjfAtq9jIv3klwqnBqGW2shhyZgyxOQGaM9hJOHwFnSWlllTw0zFV2UCllVbJ4Q6uMqgFo+ccr2ecDDwU=
    on:
      tags: true
      repo: joelfrederico/SciSalt

notifications:
  slack:
    secure: USxa0Yr5JCu2P84rIlV1LEXAQZwOnVkqQ/16aPqqpSr8QIA0kB4TmsIw+0pxrZc2/OuMpub3Yml+1ArxfEjtpyc6iJ90ED9POtqPdK364f806+fCLWeVobfSx0IQAJ6Bk9iX8IWqv8md1HBxtV4AGgeNrd6OiJYXoIHEV4yjd0kOI6v6g551E7fBTqmwYGQaPJVG7WiJLNJksZKTquW26uhQ8IISEIM91nai2KihERfmwQrVEb6ReP2WzufoJiQRjaIZVHFbtFN2nMmIiw2NbqQtlWv1/SR01uZuQzye5nh9hKi/gEbjaOGsvrTqg1lue2wY65NmLIr7lEvavro3IoCi7vqkcTq81xNc6C8KfIofTy8e5zRGp10XNMxcvnr4qdFeEh8Ze8d8CB5K0Plw7jPfh44heV413RKPmLCcjrPcwoGC5fvRU3BRGxrjems/zGqymAtMJxtJscI0j6leNoGbdp2w4tfij43zzcVDT1u3mjcm6NKWW7BNU2YG6kiSwVdModxs9/OCilEcUb+v+o8Ysc5oPgz2qgPffrRVMoF518m6IfkMszrKN4Mnn57HxqjZ9jkiWvNQx8qjCVzzD+I5KI/GHWfH15w1xxQFDInJyIDTvnjTRAVkWFs53He/YHCZ/H5VMZO1UzCFQgJRndEUfBYsuVSBshSeQZ9BvM8=
  email: false
